In [ ]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [ ]:
read=pd.read_csv('FINAL_DATASET.csv')

In [ ]:
read.shape

(66913, 9)

In [ ]:
read['SRI'].replace('', np.nan, inplace=True)

In [ ]:
read.dropna(subset=['SRI'], inplace=True)

In [ ]:
read.shape

(66600, 9)

In [ ]:
read.drop(read.index[read['SRI'] == '#NAME?'], inplace = True)

In [ ]:
read.shape

(66490, 9)

In [ ]:
target = read['Degree_of_congestion']
df1 = read.copy()
df1 = df1.drop('Degree_of_congestion', axis =1)
df1.shape

(66490, 8)

In [ ]:
le = LabelEncoder()
target = le.fit_transform(target)
target

array([3, 2, 0, ..., 0, 3, 2])

In [ ]:
target2 = df1['arrival_time']

In [ ]:
le = LabelEncoder()
arrival_time = le.fit_transform(target2)
arrival_time

array([ 834,  181,  900, ..., 4968, 5098, 5124])

In [ ]:
df1['arrival_time_new'] = arrival_time

In [ ]:
target3 = df1['trip_id']

In [ ]:
le = LabelEncoder()
trip_id = le.fit_transform(target3)
trip_id

array([3726,  355,   23, ..., 5328, 5338, 5338])

In [ ]:
df1['trip_id_new'] = trip_id

In [ ]:
df1

stop_id_from  stop_id_to  ... arrival_time_new trip_id_new
0             36156       38709  ...              834        3726
1             36156       38709  ...              181         355
2             36156       38709  ...              900          23
3             36156       38709  ...              300        5284
4             36156       38709  ...                0          22
...             ...         ...  ...              ...         ...
66908          1319        1104  ...             4842        5328
66909          1104        1106  ...             4911        5328
66910          1106        1108  ...             4968        5328
66911         39593       39385  ...             5098        5338
66912         39385       39387  ...             5124        5338

[66490 rows x 10 columns]

In [ ]:
X=df1

In [ ]:
X=X.drop('trip_id', axis=1)
X=X.drop('arrival_time', axis=1)

In [ ]:
X=X.drop('Number_of_trips', axis=1)
X=X.drop('time', axis=1)
X=X.drop('speed', axis=1)


In [ ]:
X=X.drop('SRI',axis=1)

In [ ]:
y=target

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X , y, test_size = 0.2, random_state = 42)

print("Training split input- ", X_train.shape)
print("Testing split input- ", X_test.shape)

Training split input-  (53192, 4)
Testing split input-  (13298, 4)


In [ ]:
dtree=DecisionTreeClassifier()
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = dtree.predict(X_test)
accuracy_score(y_test,y_pred)*100

62.65603850203038